### ISSUE TITLE
Suppress error transmission to connecting hosts.

### ISSUE THREAD

**Issue by silascutler** [CymmetriaResearch/MTPot#2]
When connecting.  If you send a built in command or trigger an error, it will send the python error to the connecting host.

Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Username: 
Password: 
welcome
>dir
>ps faux
>ls
>help
Help on built in commands

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/telnetsrv/telnetsrvlib.py", line 992, in handle
    self.COMMANDS[cmd](params)
  File "/usr/local/lib/python2.7/dist-packages/telnetsrv/telnetsrvlib.py", line 910, in cmdHELP
    doc = method.__doc__.split("\n")
AttributeError: 'NoneType' object has no attribute 'split'

Connection closed by foreign host.

**Comment by itamarsher** [comment]
Resolved in commit c97fd18f115609febcbc85fea351d027db1c521c.
Thanks for reporting!
