### ISSUE TITLE
suggested configuration additions

### ISSUE THREAD

**Issue by jullrich** [CymmetriaResearch/MTPot#5]
to capture other variants:

        "MIRAI": "MIRAI: applet not found",
        "DONGS": "DONGS: applet not found",
        "MEMES": "MEMES: applet not found",
	"THTC":  "THTC: applet not found",

**Comment by itamarsher** [comment]
@jullrich Since we don't have the variants readily available we won't add them without testing. If you've tested your configuration and it works please create a new conf file for each variant, open a pull request, and we'll approve it. 
Thanks for your input!
