### ISSUE TITLE
Connections hang about in CLOSE_WAIT state

### ISSUE THREAD

**Issue by madpsy** [CymmetriaResearch/MTPot#6]
I'm seeing every(?) connection hang about in a CLOSE_WAIT state and they never seem to fully close.

After a few hours MTPot needs restarted as it runs out of FDs. Example output below:

```
netstat -pn |grep 15439 | grep CLOSE_WAIT |wc -l
234
```

(15439 is the MTPot PID)

**Comment by morgajp** [comment]
A workaround for this issue is to increase the number of FDs available.  After doing this I've had the honeypot running for over 2 days without seeing this error.

```
import resource

resource.setrlimit(resource.RLIMIT_NOFILE, (65536, 65536))
```

**Comment by madpsy** [comment]
Do they eventually close or is increasing the FD's just delaying the problem?

**Comment by itamarsher** [comment]
There is an open pull request #7 by @mokaddem that should fix this problem. I've reviewed it and once fixed and merged this issue should be resolved.

**Comment by itamarsher** [comment]
The pull request has been merged. Closing this issue.
