### ISSUE TITLE
Another telnetsrv issue

### ISSUE THREAD

**Issue by bontchev** [CymmetriaResearch/MTPot#8]
When trying to run the script, I'm getting

```
c:\Work\MTPot>MTPot.py -v mirai_conf.json
Traceback (most recent call last):
  File "C:\Work\MTPot\MTPot.py", line 6, in <module>
    from telnetsrv.green import TelnetHandler, command
  File "C:\Python\lib\site-packages\telnetsrv\green.py", line 6, in <module>
    from telnetsrvlib import TelnetHandlerBase, command
  File "C:\Python\lib\site-packages\telnetsrv\telnetsrvlib.py", line 29, in <module>
    import curses.ascii
  File "C:\Python\lib\curses\__init__.py", line 15, in <module>
    from _curses import *
ImportError: No module named _curses
```

Has this script ever been tested on a Windows machine? I realize that it's not your fault that the author(s) of `telnetsrv` seem to think that the whole world is Linux, but perhaps you could contact them and suggest them to resort to `wcurses` on Windows machines or something?

**Comment by itamarsher** [comment]
The pypi entry for telnetsrv claims that it's OS independent, however I do believe the maintainer didn't really check it. Sadly the last time that library was updated was in 2012 and there are issues that are still open from 2013. I'd recommend running the script from a Linux machine because you might end up spending a lot of time porting telnetsrv/gevent to Windows. Another suggestion is to download an unofficial curses port (http://www.lfd.uci.edu/~gohlke/pythonlibs/#curses) and try again.

**Comment by bontchev** [comment]
Hm. I installed it, and the script now works without complaining - but it doesn't actually _do_ anything, which is suspicious, given how prevalent Mirai is. I would have expected hits within a few minutes.

IP is the local IP of the machine on which the script is running, right? Not its external IP?

I tried telnetting manually to the machine (using its external IP) and do get the Username/Password prompt (so the script _is_ listening). When logging in with some of the default pair of credentials (e.g., root/root), the script does display this. However, when trying any of the Mirai-related commands listed in `mirai_conf.json`, nothing happens; just the ">" prompt is displayed again. I don't get the responses specified in the config file. It is as if the commands specified there aren't recognized.

Also, when the remote telnet connection is closed, the script crashes again:

```
2017-01-08 21:38:24,986 [HoneyTelnet] DEBUG MTPot.py:115 [95.42.11.138:51739] session ended
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\Python\lib\site-packages\telnetsrv\telnetsrvlib.py", line 815, in inputcooker
    c = self._inputcooker_getc()
  File "C:\Python\lib\site-packages\telnetsrv\telnetsrvlib.py", line 776, in _inputcooker_getc
    ret = self.sock.recv(20)
  File "C:\Python\lib\site-packages\gevent\_socket2.py", line 283, in recv
    self._wait(self._read_event)
  File "C:\Python\lib\site-packages\gevent\_socket2.py", line 182, in _wait
    self.hub.wait(watcher)
  File "C:\Python\lib\site-packages\gevent\hub.py", line 651, in wait
    result = waiter.get()
  File "C:\Python\lib\site-packages\gevent\hub.py", line 899, in get
    return self.hub.switch()
  File "C:\Python\lib\site-packages\gevent\hub.py", line 630, in switch
    return RawGreenlet.switch(self)
error: [Errno 9] File descriptor was closed in another greenlet
Sun Jan 08 21:38:24 2017 <Greenlet at 0x3360340L: <bound method MyTelnetHandler.inputcooker of <__main__.MyTelnetHandler instance at 0x00000000033677C8>>> failed with error

```

**Comment by itamarsher** [comment]
This pull request ( #7 ) fixed the crash that you've experienced. 
As for the IP - if your machine is behind a NAT Mirai won't be able to scan it (it'll only scan the NAT itself), so I figure this is the case on your setup. 
Did you remember to add /bin/busybox before each command? This is how Mirai executes shell commands.

**Comment by bontchev** [comment]
I've abandoned this; it crashes too much and wouldn't collect samples anyway, so I've switched to Cowrie (which was hard enough to get to work and requires Linux, so I have to run it on a VM).

Yes, I am behind a NAT abut I've opened a port 23 tunnel through it exactly for this purpose (to have a honeypot listen for Mirai attacks).

Also, when I wrote my original comment I didn't have a good enough understanding of how Mirai works; playing with Cowrie helped me grasp that. The thing is not a virus (it doesn't self-replicate). There are normally 3 machines involved and the honeypot would see 2 distinct classes of attack patterns.

First, you have infected cameras running the bot. They just try to log in and leave immediately. This is what your honeypot logs but you can't get anything from them, since the cameras don't run a server and don't spread the bot. The bot just reports your IP as vulnerable to the C&C server.

Then the C&C server also tries to log in (not just checking for successful logins, like the bot, but also looking for writable file systems, presence of `wget`, determines the plafrom - ARM/PPC/x86, etc.).

Finally, if satisfied that your honeypot is a system suitable for infection, the C&C server sends a copy of the bot to it, usually taking it from a _third_ machine (the repository). In the original variant, it sends only a small loader (tailored for your platform), which then proceeds to download the real bot. But nowadays most variants have a single stage, meaning that the C&C server uploads directly the bot itself.

Also, there are lots of different variants around - I've found about 30 so far. It's hard to distinguish between them when watching just the communications from the bot (since it does just `enable; system; shell; sh; /bin/busybox MIRAI`) but even there, there are variants using not "MIRAI" but other strings (MM, ANNIE, MEMES, OBJPRN, THTC, MASUTA, etc.).

I tried making my own honeypot along the lines of yours, only using `twisted` instead of the library you're using (because I really wanted it to be able to run on Windows), but for some reason Mirai didn't like it (although it worked just fine when I was manually telnetting to it), so I ended up switching to Cowrie.

Anyway, back on topic. Yes, the crash when the connection is terminated is fixed, but the thing still crashes a lot. For instance, try using backspace trying to correct a telnet command you're entering - the session will disconnect and the server will show this:

```
2017-02-16 14:49:43,683 [HoneyTelnet] INFO MTPot.py:111 [127.0.0.1:56918] logon
credentials used: user:root pass:toor
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\Python\lib\site-packages\gevent\baseserver.py", line 26, in _handle_a
nd_close_when_done
    return handle(*args_tuple)
  File "C:\Python\lib\site-packages\telnetsrv\telnetsrvlib.py", line 494, in str
eamserver_handle
    cls(request, address, server)
  File "C:\Python\lib\site-packages\telnetsrv\green.py", line 14, in __init__
    TelnetHandlerBase.__init__(self, request, client_address, server)
  File "C:\Python\lib\site-packages\telnetsrv\telnetsrvlib.py", line 481, in __i
nit__
    SocketServer.BaseRequestHandler.__init__(self, request, client_address, serv
er)
  File "C:\Python\lib\SocketServer.py", line 649, in __init__
    self.handle()
  File "C:\Python\lib\site-packages\telnetsrv\telnetsrvlib.py", line 984, in han
dle
    raw_input = self.readline(prompt=self.PROMPT).strip()
  File "C:\Python\lib\site-packages\telnetsrv\telnetsrvlib.py", line 703, in rea
dline
    self._readline_echo(self.CODES['CSRLEFT'] + self.CODES['DEL'], echo)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
Thu Feb 16 14:49:48 2017 <Greenlet at 0x2ed4508L: _handle_and_close_when_done(<bound method type.streamserver_handle of <class ', <bound method StreamServer.do_close of <StreamServ, (<socket at 0x2ee3e10L fileno=424 sock=127.0.0.1:2)> failed with TypeError
```

(I'm running the honeypot on `localhost` for testing purposes and connecting to it locally.)

**Comment by charlie-the-unicorn** [comment]
@bontchev It's possible to identify the variants with MTPot. They are logged in the _executed_ line.
You have probably encountered only MIRAI in your tests.

**Comment by 0xman** [comment]
I'm having the same issue lol

**Comment by itamarsher** [comment]
Closing this issue since we don't support running MTPot on Windows.

**Comment by 0xman** [comment]
Im not running windows lmao
